/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SystemRunCounts } from './system-run-counts';

/**
 * Runtime information for the active Fabro server process.
 */
export interface SystemInfoResponse {
    /**
     * Server version string.
     */
    'version'?: string;
    /**
     * Configured public server URL for browser and CLI authentication flows.
     */
    'server_url'?: string;
    /**
     * Build git SHA when available.
     */
    'git_sha'?: string | null;
    /**
     * Build date when available.
     */
    'build_date'?: string | null;
    /**
     * Cargo build profile (e.g. `release`, `debug`) when available.
     */
    'profile'?: string | null;
    /**
     * Target operating system.
     */
    'os'?: string;
    /**
     * Target CPU architecture.
     */
    'arch'?: string;
    /**
     * Backing run storage engine.
     */
    'storage_engine'?: string;
    /**
     * Configured storage directory.
     */
    'storage_dir'?: string;
    /**
     * Seconds since this server process started.
     */
    'uptime_secs'?: number;
    'runs'?: SystemRunCounts;
    /**
     * Effective sandbox provider for launched runs.
     */
    'sandbox_provider'?: string;
    /**
     * Engine capabilities this server advertises, so a client can refuse to send grammar an older server would silently ignore. Additive: absent on servers that predate the field. Known values: `acp.fallback_chain.v1` (ordered ACP candidate failover within one node visit).
     */
    'capabilities'?: Array<string>;
}
